cache: false


services:
  - docker

script:
  - export HOSTNAME=myhost
  - docker build -t qwazer/oracle-xe-11g .
  - docker run --name oracle2 -h myhost -d -p 127.0.0.1:49161:1521 -e ORACLE_ALLOW_REMOTE=true qwazer/oracle-xe-11g
  - docker inspect oracle2
  - docker ps -a
#  - docker exec -i oracle2 bash -c 'cat /u01/app/oracle/product/11.2.0/xe/network/admin/listener.ora'
#  - docker exec -i oracle2 bash -c 'cat /u01/app/oracle/product/11.2.0/xe/network/admin/tnsnames.ora'
#  - docker exec -i oracle2 bash -c 'sed -i "s/6766fe1c072d/$HOSTNAME/g" /u01/app/oracle/product/11.2.0/xe/network/admin/listener.ora'
#  - docker exec -i oracle2 bash -c 'sed -i "s/6766fe1c072d/$HOSTNAME/g" /u01/app/oracle/product/11.2.0/xe/network/admin/tnsnames.ora'
#  - echo "Wait to allow Oracle to be initialized"
#  - travis_wait sleep 20
  - docker exec -i oracle2 bash -c 'cat /u01/app/oracle/product/11.2.0/xe/network/admin/listener.ora'
  - docker exec -i oracle2 bash -c 'cat /u01/app/oracle/product/11.2.0/xe/network/admin/tnsnames.ora'
  - docker exec -i oracle2 bash -c 'service oracle-xe stop'
  - travis_wait sleep 600
  - docker exec -i oracle2 /usr/sbin/startup.sh
  - docker exec -i oracle2 bash -c 'cat /u01/app/oracle/product/11.2.0/xe/network/admin/listener.ora'
  - docker exec -i oracle2 bash -c 'cat /u01/app/oracle/product/11.2.0/xe/network/admin/tnsnames.ora'


