
services:
  - docker

script:
  - docker build -t wnameless/oracle-xe-11g .
  - docker run --name oracle -d -p 127.0.0.1:49161:1521 -e ORACLE_ALLOW_REMOTE=true wnameless/oracle-xe-11g
  - docker inspect oracle
  - docker ps -a
  - echo "Wait to allow Oracle to be initialized"
  - travis_wait sleep 300
  - docker exec -i oracle bash -c '/u01/app/oracle/product/11.2.0/xe/bin/lsnrctl stop'
  - docker exec -i oracle bash -c '/u01/app/oracle/product/11.2.0/xe/bin/lsnrctl start'


